# Generated by Django 3.0.5 on 2021-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='datedeNaissance',
            field=models.DateField(),
        ),
    ]
